### PR TITLE
fix(climc): auto enable storage when switch s3 on

### PR DESCRIPTION
**Pull request by ioito**
**What this PR does / why we need it**:

- [x] Smoke testing completed

If yes, write the release branches name in the below format and submit the related cherry-pick PR:
- release/3.11

### CODE REVIEW

**Comment by swordqiu** [comment]
其他对象存储的driver也需要支持：ceph, xsky

**Comment by ioito** [comment]
> 其他对象存储的driver也需要支持：ceph, xsky

已更新

**Pull request merged**
